import process from "node:process";
import builtins from "builtin-modules";
import esbuild from "esbuild";
import { readFileSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const config: esbuild.BuildOptions = {
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
    define: {
        "import.meta.env.MODE": JSON.stringify(
            prod ? "production" : "development",
        ),
        "import.meta.env.PROD": String(prod),
        "import.meta.env.DEV": String(!prod),
    },
    plugins: [
        {
            name: "obsidian-svg-loader",
            setup(build) {
                const reg = /<\/?svg(.+)?>/g;
                build.onLoad({ filter: /\.svg/ }, (args) => {
                    const contents = readFileSync(args.path, "utf-8")
                        .replace(reg, "")
                        .replace(/black/g, "currentColor")
                        .trim();
                    return {
                        contents,
                        loader: "text",
                    };
                });
            },
        },
    ],
};

if (prod) {
    const context = await esbuild.context(config);
    await context.rebuild();
    process.exit(0);
} else {
    const context = await esbuild.context({
        ...config,
        outfile: "./demo/.obsidian/plugins/pochoir/main.js",
    });
    await context.watch();
}
